### PR TITLE
docs(localstack): fix localstack example by setting `force_path_style`

### LINKED ISSUE #131: Error running localstack example ("failed to look up address information")
### Describe the bug

Running the `localstack` example throws an error:
```
Error: Unhandled(
    Unhandled {
        source: DispatchFailure(
            DispatchFailure {
                source: ConnectorError {
                    kind: Io,
                    source: hyper::Error(
                        Connect,
                        ConnectError(
                            "dns error",
                            Custom {
                                kind: Uncategorized,
                                error: "failed to lookup address information: nodename nor servname provided, or not known"
                            }
                        )
                    ),
                    connection: Unknown
                }
            }
        ),
        meta: ErrorMetadata {
            code: None,
            message: None,
            extras: None
        }
    }
)
```

As well as a warning:
```
warning: use of deprecated associated function `aws_config::BehaviorVersion::v2023_11_09`: Superceded by v2024_03_28, which enabled stalled stream protection for uploads (request bodies) by default.
  --> examples/localstack.rs:22:56
   |
22 |     let config = aws_config::defaults(BehaviorVersion::v2023_11_09())
   |                                                        ^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
```

### To Reproduce

Run from repo root:
```sh
cargo run --example localstack --features="localstack"  
```

Version information:
```
❯❯❯ uname -a 
Darwin Neils-Air.lan 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103 arm64
❯❯❯ rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)
❯❯❯ cargo --version
cargo 1.77.2 (e52e36006 2024-03-26)
❯❯❯ docker --version
Docker version 24.0.6, build ed223bc
```

### Expected behavior

Successful run of example.

### PR DESCRIPTION
**Pull request by neilyio**
Closes #131, where I discovered the `localstack` example is broken when running:
```
cargo run --example localstack --features="localstack" 
```

Some research brought me to [awslabs/aws-sdk-rust#1138](https://github.com/awslabs/aws-sdk-rust/issues/1138), which uncovered that `create_bucket` is broken here because `localstack` uses the soon-to-be-deprecated ["path-style"](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) address style rather than the newer "virutal-hosted" style.

I reworked the configuration in the example to set `force_path_style(true)`, which fixes `create_bucket`. The example now runs successfully.

I also updated the `BehaviorVersion`, because the currently referenced one is now deprecated and was causing a warning.

### CODE REVIEW

File: examples/localstack.rs
Comment (DDtKey) [inline examples/localstack.rs:1]: Thanks for the quick fix of the example!

I'd suggest to add logging into the beginning of the `main` function
```rs
let _ = pretty_env_logger::try_init();
```

It's much easier to find such issues with logging in examples, with trace or debug logging we can find the issue really fast:

```log
TRACE aws_smithy_runtime::client::orchestrator                > transmitting request request=Request { body: SdkBody { inner: Once(Some(b"")), retryable: true }, uri: Uri { as_string: "http://example-bucket.localhost:55209/", parsed: H0(http://example-bucket.localhost:55209/) }, method: PUT, extensions: Extensions { extensions_02x: Extensions, extensions_1x: Extensions }, headers: Headers { headers: {"content-type": HeaderValue { _private: H0("application/xml") }, "content-length": HeaderValue { _private: H0("0") }, "user-agent": HeaderValue { _private: H0("aws-sdk-rust/1.1.5 os/macos lang/rust/1.77.1") }, "x-amz-user-agent": HeaderValue { _private: H0("aws-sdk-rust/1.1.5 api/s3/1.15.0 os/macos lang/rust/1.77.1") }, "x-amz-date": HeaderValue { _private: H0("20240510T194007Z") }, "authorization": HeaderValue { _private: H0("AWS4-HMAC-SHA256 Credential=fake/20240510/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=fd2df67b8672fd7a0b487423355006b4b22da573778474083bd943b4bdd688ed") }, "x-amz-content-sha256": HeaderValue { _private: H0("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855") }, "amz-sdk-request": HeaderValue { _private: H0("attempt=1; max=3") }, "amz-sdk-invocation-id": HeaderValue { _private: H0("2d52510e-4532-47e6-96ec-9d27f407b2f0") }} } }
...
DEBUG hyper::client::connect::dns                             > resolving host="example-bucket.localhost"
```

File: examples/localstack.rs [hunk 1]
```diff
@@ -14,19 +14,19 @@ async fn main() -> Result<(), s3::Error> {
...
-
     // Set up AWS client
     let endpoint_url = format!("http://{host_ip}:{host_port}");
-    let region_provider = RegionProviderChain::default_provider().or_else("us-east-1");
     let creds = s3::config::Credentials::new("fake", "fake", None, None, "test");
-    let config = aws_config::defaults(BehaviorVersion::v2023_11_09())
-        .region(region_provider)
+
+    let config = aws_sdk_s3::config::Builder::default()
+        .behavior_version(BehaviorVersion::v2024_03_28())
```
Comment (DDtKey) [inline examples/localstack.rs:24]: This one, in fact - not required change, because depends on your `Cargo.lock` (e.g - I have `aws-smithy-runtime 1.1.6` in it - where `v2024_03_28` doesn't present, and it corresponds to minimal versions declared in `Cargo.toml`). 

But let's keep it, since it's more fresh version

**Comment by DDtKey** [comment]
Thank you for the contribution! 🙏
